name: Rust

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.file }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        file:
          # - ${{ github.event.repository.name }}
          - bin1
          - bin2
    runs-on: ${{ matrix.os }}
    # outputs:
      # artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@master
      - name: Build
        env:
          CARGO_TERM_COLOR: always
        run: cargo build --release --verbose
      - name: Upload
        uses: actions/upload-artifact@master
        id: artifact-upload-step
        with:
          name: Binary-${{ matrix.file }}-${{ matrix.os }}
          path: target/release/${{ matrix.file }}${{ runner.os == 'Windows' && '.exe' || '' }}
      # - name: Output artifact URL
      #   run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'

  release:
    name: downloading Binary-${{ matrix.file }}-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        file:
          # - ${{ github.event.repository.name }}
          - bin1
          - bin2
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@master
        with:
          name: Binary-${{ matrix.file }}-${{ matrix.os }}
      - name: List files
        run: |
          ls -lih
      - name: GH Release for ${{ matrix.os }}
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: '*'
      - name: Done
        run: |
          echo "### [${{ github.ref_name }}](https://github.com/$GITHUB_REPOSITORY/releases/tag/${{ github.ref_name }}) Released! :rocket:" >> $GITHUB_STEP_SUMMARY
