name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    outputs:
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --release --verbose
      - name: Upload
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: Binary
          path: |
            target/release/hi-rust-release*
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-url }}'

  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: cat /etc/os-release
      - uses: actions/download-artifact@master
        with:
          name: Binary
      - run: ls -lih

permissions:
  contents: write
