name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            file: target/release/hi-rust-release.exe
          - os: ubuntu-latest
            file: target/release/hi-rust-release
    runs-on: ${{ matrix.os }}
    outputs:
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --release --verbose
      - name: Upload
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: Binary-${{ matrix.os }}
          path: ${{ matrix.file }}
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-url }}'

  build2:
    name: downloading Binary-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: cat /etc/os-release
      - uses: actions/download-artifact@master
        with:
          name: Binary-${{ matrix.os }}
      - run: ls -lih
      - name: GH Release for ${{ matrix.os }}
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            hi-rust-release*

permissions:
  contents: write
